In [2]:
import numpy as np

### Concatenation in numpy array

In [ ]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([2, 2, 2 ,2])



In [4]:
arr1, arr2

(array([1, 2, 3, 4]), array([2, 2, 2, 2]))

In [5]:
arr3 = np.concatenate((arr1, arr2))

In [6]:
arr3

array([1, 2, 3, 4, 2, 2, 2, 2])

In [9]:
arr1, arr2

(array([1, 2, 3, 4]), array([2, 2, 2, 2]))

In [ ]:
arr4 = np.concatenate((arr1, arr2), axis=0)

In [11]:
arr4

array([1, 2, 3, 4, 2, 2, 2, 2])

In [13]:
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[2, 2, 2 ,2]])

In [14]:
arr3 = np.concatenate((arr1, arr2), axis = 0)

In [15]:
arr3

array([[1, 2, 3, 4],
       [2, 2, 2, 2]])

In [16]:
arr4 = np.concatenate((arr1, arr2), axis = 1)
arr4

array([[1, 2, 3, 4, 2, 2, 2, 2]])

In [17]:
array5 = np.array([[4, 5, 6, 8],
                   [9, 9, 9, 9]])
array6 = np.array([[6, 6, 6, 6],
                   [1, 1, 1, 1]])

In [18]:
np.concatenate((array5, array6), axis=1)

array([[4, 5, 6, 8, 6, 6, 6, 6],
       [9, 9, 9, 9, 1, 1, 1, 1]])

In [19]:
np.concatenate((array5, array6), axis=0)

array([[4, 5, 6, 8],
       [9, 9, 9, 9],
       [6, 6, 6, 6],
       [1, 1, 1, 1]])

In [20]:
np.vstack((array5, array6))

array([[4, 5, 6, 8],
       [9, 9, 9, 9],
       [6, 6, 6, 6],
       [1, 1, 1, 1]])

In [21]:
np.hstack((array5, array6))

array([[4, 5, 6, 8, 6, 6, 6, 6],
       [9, 9, 9, 9, 1, 1, 1, 1]])

In [22]:
array7 = np.array([[1, 2, 3],
                  [4, 5, 6]])
array8 = np.array([[2, 2, 2]])


In [24]:
np.vstack((array7, array8))

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 2]])

In [25]:
array9 = np.array([[10], [10]])
array9

array([[10],
       [10]])