In [1]:
import numpy as np

In [2]:
array1 = np.linspace(-np.pi, np.pi, 10)
array1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [4]:
sin_value = np.sin(array1)


In [5]:
sin_value

array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

In [6]:
sin_value = np.round(sin_value, 3)

In [7]:
sin_value

array([-0.   , -0.643, -0.985, -0.866, -0.342,  0.342,  0.866,  0.985,
        0.643,  0.   ])

## using mean in numpy array

In [8]:
array1 = np.array([1, 5, 7, 8])
mean = np.mean(array1)

In [10]:
print(mean)

5.25


In [11]:
array2 = np.array([[6, 7, 8, 10],
                   [8, 3, 5, 12],
                   [10, 23, 4, 6],
                   [10, 12, 16, 18]])


In [12]:
array2

array([[ 6,  7,  8, 10],
       [ 8,  3,  5, 12],
       [10, 23,  4,  6],
       [10, 12, 16, 18]])

In [13]:
mean = np.mean(array2)

In [14]:
print(mean)

9.875


In [16]:
mean_1 = np.mean(array2, axis = 0)
mean_1

array([ 8.5 , 11.25,  8.25, 11.5 ])

### Random number in numpy

In [22]:
# rand
# randint

rand_array1 = np.random.rand(4, 4)
rand_array1

array([[0.435161  , 0.32522589, 0.35005525, 0.20205576],
       [0.40581621, 0.83771013, 0.78406712, 0.09612489],
       [0.97302298, 0.98841893, 0.12824346, 0.33408163],
       [0.64708135, 0.64490021, 0.01984905, 0.8246181 ]])

In [23]:
randint_array = np.random.randint(10, 20, size= (4, 5))

In [24]:
randint_array

array([[12, 17, 10, 15, 14],
       [19, 17, 11, 12, 10],
       [17, 12, 13, 18, 15],
       [13, 17, 11, 19, 16]], dtype=int32)

### Split() method in numpy array

In [4]:
import numpy as np

In [5]:
array_1 = np.random.randint(10, 51, size=(5, 6))
array_1

array([[29, 33, 44, 36, 34, 19],
       [36, 45, 49, 24, 50, 24],
       [14, 24, 47, 32, 40, 10],
       [21, 41, 22, 46, 30, 49],
       [21, 49, 40, 48, 37, 11]], dtype=int32)

In [10]:
array_first, array_second = np.split(array_1, [3],axis=0)

In [11]:
array_first

array([[29, 33, 44, 36, 34, 19],
       [36, 45, 49, 24, 50, 24],
       [14, 24, 47, 32, 40, 10]], dtype=int32)

In [12]:
array_columnpart1, array_columnpart2 = np.split(array_1, [3],axis=1)

In [13]:
array_columnpart1

array([[29, 33, 44],
       [36, 45, 49],
       [14, 24, 47],
       [21, 41, 22],
       [21, 49, 40]], dtype=int32)

In [14]:
array_columnpart2

array([[36, 34, 19],
       [24, 50, 24],
       [32, 40, 10],
       [46, 30, 49],
       [48, 37, 11]], dtype=int32)

In [15]:

array_columnpart1, array_columnpart2, array_columnpart3 = np.split(array_1, [2, 4],axis=1)

In [16]:
array_columnpart1.shape

(5, 2)

In [17]:
array_columnpart2.shape

(5, 2)

In [18]:
array_columnpart3.shape

(5, 2)

### Loading the data from txt 

In [23]:
iris_array = np.genfromtxt(r"C:\Users\Lenovo\Desktop\Python-ML-Training-Arniko-college\Araniko_Morning\Numpy_Learning\iris.txt", delimiter=',', dtype=str)

In [27]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [28]:
features, labels = np.split(iris_array, [4], axis=1)

In [29]:
features.shape

(150, 4)

In [30]:
labels.shape

(150, 1)

In [31]:
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

In [32]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [33]:
features = features.astype(float)

In [34]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [35]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [36]:
mean_feature = np.mean(features, axis = 0)

In [38]:
mean_feature

array([5.84333333, 3.054     , 3.75866667, 1.19866667])