In [1]:
import numpy as np

### Creating numpy array

In [2]:

arr1 = np.array([3, 5, 6, 8, 10])
print(arr1)
print(type(arr1))

[ 3  5  6  8 10]
<class 'numpy.ndarray'>


### creating two dimensional array

In [3]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### to check the dimension of the array


In [4]:
array_2d.ndim

2

In [5]:
arr1.ndim

1

In [6]:
### create a three dimensional array

In [7]:
array_3d = np.array([[[1, 3, 4], [4, 5, 6]],
                     [[7, 8, 9], [11, 12, 13]]])
array_3d

array([[[ 1,  3,  4],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [8]:
arr_100 = np.arange(1, 101)
arr_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [9]:
### linspace
arr2 = np.linspace(1, 5, 10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


#### Creating zero, ones and identity matrix

In [10]:
arr_zero = np.zeros((8, 8), dtype=int)
arr_zero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
arr_ones = np.ones((8, 8), dtype=int)
arr_ones

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [12]:
arr_indentity = np.eye(8)

In [13]:
arr_indentity

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [14]:
### to check the shape of nd array
arr_indentity.shape

(8, 8)

In [15]:
array_3d.shape

(2, 2, 3)

In [16]:
arr1 = np.array([4, 5, 7, 9])
arr2 = np.array([2, 5, 8, 10])
print(arr1 + arr2)

[ 6 10 15 19]


In [17]:
arr2d1 = np.array([[3, 4, 5], [6, 7, 8], [1, 3, 5]])
arr2d2 = np.array([[1, 2, 3], [5, 6, 3], [8, 6, 1]])
print(arr2d1 * arr2d2)

[[ 3  8 15]
 [30 42 24]
 [ 8 18  5]]


In [18]:
arr2d1 = np.array([[3, 4, 5], [6, 7, 8], [1, 3, 5]])
arr2d2 = np.array([[1, 2, 3], [5, 6, 3], [8, 6, 1]])
print(arr2d1 @ arr2d2)

[[ 63  60  26]
 [105 102  47]
 [ 56  50  17]]


### Creating multidimensional array

In [19]:

array1 = np.array([2, 3, 4, 5], ndmin=5)
array1

array([[[[[2, 3, 4, 5]]]]])

In [20]:
array1.shape

(1, 1, 1, 1, 4)

#### Operation in array

In [21]:
array1 = np.array([4, 8, 9, 12])
print(array1 + 10)
### Vectorization in numpy array

[14 18 19 22]


In [22]:
array1

array([ 4,  8,  9, 12])

### Indexing in numpy array

In [23]:
print(array1[1])

8


In [24]:
array2 = np.array([[1, 2, 3, 4], [6, 7, 3, 4], [10, 18, 19, 14]])
array2

array([[ 1,  2,  3,  4],
       [ 6,  7,  3,  4],
       [10, 18, 19, 14]])

In [25]:
print(array2[1, 1])

7


### Slicing in numpy array

In [26]:
array2

array([[ 1,  2,  3,  4],
       [ 6,  7,  3,  4],
       [10, 18, 19, 14]])

In [27]:
# array2[start_row:end_row, start_column:end_column]
array2[0:2, 0:4]

array([[1, 2, 3, 4],
       [6, 7, 3, 4]])

In [28]:
array2[0:2, :]

array([[1, 2, 3, 4],
       [6, 7, 3, 4]])

### Reshaping an array

In [29]:
array2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

In [30]:
array2d.shape

(3, 4)

In [31]:
array2d_reshape = array2d.reshape(1, 12)
array2d_reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [32]:
array2d_reshape.shape

(1, 12)

In [33]:
array2d_1d = array2d.reshape(12)
array2d_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [34]:
array2d_1d.reshape(6, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

To store 1 to 100
2-dimensional array
shape: (5, 20)


In [36]:
array1d = np.arange(1, 101)
array1d.shape

(100,)

In [37]:
array2d = array1d.reshape(5, 20)

In [38]:
array2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [39]:
array2d.shape

(5, 20)