In [1]:
import numpy as np

### Creating numpy array

In [3]:

arr1 = np.array([3, 5, 6, 8, 10])
print(arr1)
print(type(arr1))

[ 3  5  6  8 10]
<class 'numpy.ndarray'>


### creating two dimensional array

In [4]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### to check the dimension of the array


In [5]:
array_2d.ndim

2

In [6]:
arr1.ndim

1

In [7]:
### create a three dimensional array

In [8]:
array_3d = np.array([[[1, 3, 4], [4, 5, 6]],
                     [[7, 8, 9], [11, 12, 13]]])
array_3d

array([[[ 1,  3,  4],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [11, 12, 13]]])

In [9]:
arr_100 = np.arange(1, 101)
arr_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [11]:
### linspace
arr2 = np.linspace(1, 5, 10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


#### Creating zero, ones and identity matrix

In [14]:
arr_zero = np.zeros((8, 8), dtype=int)
arr_zero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
arr_ones = np.ones((8, 8), dtype=int)
arr_ones

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [16]:
arr_indentity = np.eye(8)

In [17]:
arr_indentity

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
### to check the shape of nd array
arr_indentity.shape

(8, 8)

In [19]:
array_3d.shape

(2, 2, 3)

In [20]:
arr1 = np.array([4, 5, 7, 9])
arr2 = np.array([2, 5, 8, 10])
print(arr1 + arr2)

[ 6 10 15 19]


In [21]:
arr2d1 = np.array([[3, 4, 5], [6, 7, 8], [1, 3, 5]])
arr2d2 = np.array([[1, 2, 3], [5, 6, 3], [8, 6, 1]])
print(arr2d1 * arr2d2)

[[ 3  8 15]
 [30 42 24]
 [ 8 18  5]]


In [22]:
arr2d1 = np.array([[3, 4, 5], [6, 7, 8], [1, 3, 5]])
arr2d2 = np.array([[1, 2, 3], [5, 6, 3], [8, 6, 1]])
print(arr2d1 @ arr2d2)

[[ 63  60  26]
 [105 102  47]
 [ 56  50  17]]
