### Concatenation in numpy array

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.concatenate((arr1, arr2))

In [4]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

### for two dimensional array

In [5]:
arr2d1 = np.array([[1, 2, 3, 4],
                  [5, 6 ,7, 8],
                  [9, 10, 11, 13]])
arr2d2 = np.array([[14, 15, 16, 17],
                   [18, 19, 20, 21],
                   [22, 23, 24, 25]])


In [6]:
np.concatenate((arr2d1, arr2d2), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [7]:
np.concatenate((arr2d1, arr2d2), axis=1)

array([[ 1,  2,  3,  4, 14, 15, 16, 17],
       [ 5,  6,  7,  8, 18, 19, 20, 21],
       [ 9, 10, 11, 13, 22, 23, 24, 25]])

## hstack and vstack

In [8]:
arr1 = np.array([[7, 8, 10, 11],
                 [12, 16, 18, 20]])
arr2 = np.array([[2, 2, 2, 2]])

In [10]:
np.vstack((arr1, arr2))

array([[ 7,  8, 10, 11],
       [12, 16, 18, 20],
       [ 2,  2,  2,  2]])

In [11]:
arr3 = np.array([[23],
                 [34]])

In [13]:
np.hstack((arr1, arr3))

array([[ 7,  8, 10, 11, 23],
       [12, 16, 18, 20, 34]])

### Slicing in numpy array

In [14]:
array1 = np.arange(1, 11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
array2 = array1[3:7]
array2

array([4, 5, 6, 7])

## for two dimensional array

In [16]:
array2 = np.array([[4, 5, 6, 7],
                   [12, 14, 56, 20],
                   [18, 23, 45, 68]])
array2.shape

(3, 4)

In [17]:
array2.ndim

2

In [19]:
print(array2[1, 1])

14


In [20]:
print(array2[2, 0])

18


In [21]:
print(array2[1:3, 1:3])

[[14 56]
 [23 45]]


In [22]:
print(array2[0:, 1:3])

[[ 5  6]
 [14 56]
 [23 45]]


### Reshaping in numpy array

In [23]:
array2

array([[ 4,  5,  6,  7],
       [12, 14, 56, 20],
       [18, 23, 45, 68]])

In [24]:
array2.shape

(3, 4)

In [25]:
array2.reshape(4, 3)

array([[ 4,  5,  6],
       [ 7, 12, 14],
       [56, 20, 18],
       [23, 45, 68]])

In [27]:
array2.reshape(12)

array([ 4,  5,  6,  7, 12, 14, 56, 20, 18, 23, 45, 68])

In [28]:
array2.reshape(2, 3, 2)

array([[[ 4,  5],
        [ 6,  7],
        [12, 14]],

       [[56, 20],
        [18, 23],
        [45, 68]]])

In [29]:
### store the element from 1 to hundred in 2d array of shape (20, 5)

In [30]:
array_100 = np.arange(1, 101)
array_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [31]:
array_100.reshape(20, 5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])