In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 3, 5, 6, 8])
array1

array([1, 3, 5, 6, 8])

## Two dimensional array

In [3]:
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Three dimensional array

In [4]:
array3 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]],
    [[13, 14, 15], [16, 17, 18]]
])
print(array3)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


## to check the dimension of the array

In [6]:
array1.ndim ## give the dimension of the array

1

In [7]:
array2.ndim

2

In [8]:
array3.ndim

3

### Shape of the array

In [9]:

array1.shape

(5,)

In [10]:
array2.shape

(3, 3)

In [11]:
array3.shape

(3, 2, 3)

### Size of the array

In [12]:
array1.size

5

In [13]:
array2.size

9

In [14]:
array3.size

18

### Arange function in numpy array

In [15]:
array1 = np.arange(1, 101, 1)

In [16]:
array1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [17]:
odd_array = np.arange(1, 101, 2)
odd_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## linspace() in numpy array

In [19]:
array2 = np.linspace(1, 10, 5)
array2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

### Arithmetic operation in numpy

In [20]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)

[1, 2, 3, 4, 5, 6]


In [21]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
print(arr1 + arr2)

[ 6  8 10 12]


In [22]:
arr3 = np.array([[4, 6, 7],
                [8, 4, 3],
                [9, 2, 1]])
arr4 = np.array([[6, 7, 7],
                [5, 4, 3],
                [3, 2, 1]])

arr3, arr4

(array([[4, 6, 7],
        [8, 4, 3],
        [9, 2, 1]]),
 array([[6, 7, 7],
        [5, 4, 3],
        [3, 2, 1]]))

In [23]:
arr3 * arr4

array([[24, 42, 49],
       [40, 16,  9],
       [27,  4,  1]])

## for matrix multiplication

In [24]:
arr3 @ arr4

array([[75, 66, 53],
       [77, 78, 71],
       [67, 73, 70]])