In [1]:
import numpy as np

### Learning array in numpy

In [2]:
### 1d array(one dimension array)

array_1d = np.array([1, 3, 4, 5, 6])
array_1d


array([1, 3, 4, 5, 6])

### Two dimensional array

In [3]:
array_2d = np.array([[2, 3, 4], [5, 6, 7], [8, 9, 10]])
print(array_2d)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


### Three dimensional array
--> collection of 2d array

In [4]:
array_3d = np.array([[[1, 2, 3],
                       [4, 5, 6]],
                    [[7, 8, 9],
                    [10, 11, 12]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### to check the dimension of the array

In [5]:
array_3d.ndim

3

In [6]:
array_2d.ndim

2

### one dimension array

In [7]:

array_1d = np.arange(1, 101, 2)
array_1d

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

### Linspace method

In [8]:
array_1d = np.linspace(1, 5, 10)
array_1d

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])