### Concatenation in numpy array

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.concatenate((arr1, arr2))

In [3]:
arr3

array([1, 2, 3, 4, 5, 6, 7, 8])

### for two dimensional array

In [4]:
arr2d1 = np.array([[1, 2, 3, 4],
                  [5, 6 ,7, 8],
                  [9, 10, 11, 13]])
arr2d2 = np.array([[14, 15, 16, 17],
                   [18, 19, 20, 21],
                   [22, 23, 24, 25]])


In [5]:
np.concatenate((arr2d1, arr2d2), axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [6]:
np.concatenate((arr2d1, arr2d2), axis=1)

array([[ 1,  2,  3,  4, 14, 15, 16, 17],
       [ 5,  6,  7,  8, 18, 19, 20, 21],
       [ 9, 10, 11, 13, 22, 23, 24, 25]])

## hstack and vstack

In [7]:
arr1 = np.array([[7, 8, 10, 11],
                 [12, 16, 18, 20]])
arr2 = np.array([[2, 2, 2, 2]])

In [8]:
np.vstack((arr1, arr2))

array([[ 7,  8, 10, 11],
       [12, 16, 18, 20],
       [ 2,  2,  2,  2]])

In [9]:
arr3 = np.array([[23],
                 [34]])

In [10]:
np.hstack((arr1, arr3))

array([[ 7,  8, 10, 11, 23],
       [12, 16, 18, 20, 34]])

### Slicing in numpy array

In [11]:
array1 = np.arange(1, 11)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
array2 = array1[3:7]
array2

array([4, 5, 6, 7])

## for two dimensional array

In [13]:
array2 = np.array([[4, 5, 6, 7],
                   [12, 14, 56, 20],
                   [18, 23, 45, 68]])
array2.shape

(3, 4)

In [14]:
array2.ndim

2

In [15]:
print(array2[1, 1])

14


In [16]:
print(array2[2, 0])

18


In [17]:
print(array2[1:3, 1:3])

[[14 56]
 [23 45]]


In [18]:
print(array2[0:, 1:3])

[[ 5  6]
 [14 56]
 [23 45]]


### Reshaping in numpy array

In [19]:
array2

array([[ 4,  5,  6,  7],
       [12, 14, 56, 20],
       [18, 23, 45, 68]])

In [20]:
array2.shape

(3, 4)

In [21]:
array2.reshape(4, 3)

array([[ 4,  5,  6],
       [ 7, 12, 14],
       [56, 20, 18],
       [23, 45, 68]])

In [22]:
array2.reshape(12)

array([ 4,  5,  6,  7, 12, 14, 56, 20, 18, 23, 45, 68])

In [23]:
array2.reshape(2, 3, 2)

array([[[ 4,  5],
        [ 6,  7],
        [12, 14]],

       [[56, 20],
        [18, 23],
        [45, 68]]])

In [24]:
### store the element from 1 to hundred in 2d array of shape (20, 5)

In [25]:
array_100 = np.arange(1, 101)
array_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [26]:
array_100.reshape(20, 5)

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45],
       [ 46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55],
       [ 56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75],
       [ 76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85],
       [ 86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100]])

# Random array in numpy

In [27]:
# rand() - gives the random values between 0 and 1
# randint() - give the random integer value with in the specified range

In [28]:
array_1 = np.random.rand(4, 6)

In [29]:
array_1

array([[0.27353261, 0.35481298, 0.96228628, 0.77663853, 0.89073974,
        0.72345049],
       [0.36893879, 0.14350587, 0.04484824, 0.31342492, 0.1754171 ,
        0.32786284],
       [0.24258874, 0.16597876, 0.4658141 , 0.66476927, 0.80644742,
        0.58424109],
       [0.55546628, 0.77092094, 0.6664759 , 0.06548058, 0.66426136,
        0.05710207]])

In [30]:
array_2 = np.random.rand(10)

In [31]:
array_2

array([0.55292321, 0.7937293 , 0.26515782, 0.12738222, 0.07845359,
       0.18782236, 0.70919293, 0.51256945, 0.5445708 , 0.33290329])

### randint method 

In [32]:
array_3 = np.random.randint(10, 15, size=(7))

In [33]:
array_3

array([10, 11, 13, 13, 10, 14, 12], dtype=int32)

### Splitting in numpy array

In [40]:
array1 = np.random.randint(100, 500, size = (9, 6))

In [41]:
array1

array([[116, 283, 102, 468, 457, 368],
       [124, 439, 284, 292, 168, 313],
       [152, 254, 394, 280, 205, 340],
       [182, 373, 271, 377, 130, 276],
       [415, 377, 193, 427, 300, 434],
       [102, 365, 102, 406, 302, 350],
       [371, 458, 478, 335, 453, 253],
       [203, 397, 318, 180, 316, 222],
       [199, 406, 203, 392, 475, 312]], dtype=int32)

In [42]:
array1_1, array1_2, array1_3 = np.split(array1, 3, axis=0)

In [43]:
array1_1

array([[116, 283, 102, 468, 457, 368],
       [124, 439, 284, 292, 168, 313],
       [152, 254, 394, 280, 205, 340]], dtype=int32)

In [44]:
array1_2

array([[182, 373, 271, 377, 130, 276],
       [415, 377, 193, 427, 300, 434],
       [102, 365, 102, 406, 302, 350]], dtype=int32)

In [45]:
array1_3


array([[371, 458, 478, 335, 453, 253],
       [203, 397, 318, 180, 316, 222],
       [199, 406, 203, 392, 475, 312]], dtype=int32)

### Columnwise splitting

In [46]:
array1 = np.random.randint(100, 500, size = (10, 6))

In [47]:
array1

array([[196, 144, 321, 195, 287, 407],
       [130, 438, 218, 419, 436, 359],
       [357, 195, 104, 321, 129, 381],
       [123, 470, 209, 223, 135, 441],
       [126, 398, 379, 292, 482, 169],
       [426, 256, 261, 409, 318, 402],
       [270, 427, 461, 124, 473, 266],
       [268, 481, 257, 320, 352, 357],
       [315, 303, 215, 380, 385, 391],
       [173, 465, 130, 237, 324, 419]], dtype=int32)

In [48]:
array1_1, array1_2 = np.split(array1, 2, axis=1)

In [49]:
array1_2

array([[195, 287, 407],
       [419, 436, 359],
       [321, 129, 381],
       [223, 135, 441],
       [292, 482, 169],
       [409, 318, 402],
       [124, 473, 266],
       [320, 352, 357],
       [380, 385, 391],
       [237, 324, 419]], dtype=int32)

In [50]:
array1_1

array([[196, 144, 321],
       [130, 438, 218],
       [357, 195, 104],
       [123, 470, 209],
       [126, 398, 379],
       [426, 256, 261],
       [270, 427, 461],
       [268, 481, 257],
       [315, 303, 215],
       [173, 465, 130]], dtype=int32)

In [51]:
array1

array([[196, 144, 321, 195, 287, 407],
       [130, 438, 218, 419, 436, 359],
       [357, 195, 104, 321, 129, 381],
       [123, 470, 209, 223, 135, 441],
       [126, 398, 379, 292, 482, 169],
       [426, 256, 261, 409, 318, 402],
       [270, 427, 461, 124, 473, 266],
       [268, 481, 257, 320, 352, 357],
       [315, 303, 215, 380, 385, 391],
       [173, 465, 130, 237, 324, 419]], dtype=int32)

In [52]:
array1_1, array1_2 = np.split(array1, [5], axis=1)

In [53]:
array1_1

array([[196, 144, 321, 195, 287],
       [130, 438, 218, 419, 436],
       [357, 195, 104, 321, 129],
       [123, 470, 209, 223, 135],
       [126, 398, 379, 292, 482],
       [426, 256, 261, 409, 318],
       [270, 427, 461, 124, 473],
       [268, 481, 257, 320, 352],
       [315, 303, 215, 380, 385],
       [173, 465, 130, 237, 324]], dtype=int32)

In [54]:
array1_2

array([[407],
       [359],
       [381],
       [441],
       [169],
       [402],
       [266],
       [357],
       [391],
       [419]], dtype=int32)

In [55]:
array1

array([[196, 144, 321, 195, 287, 407],
       [130, 438, 218, 419, 436, 359],
       [357, 195, 104, 321, 129, 381],
       [123, 470, 209, 223, 135, 441],
       [126, 398, 379, 292, 482, 169],
       [426, 256, 261, 409, 318, 402],
       [270, 427, 461, 124, 473, 266],
       [268, 481, 257, 320, 352, 357],
       [315, 303, 215, 380, 385, 391],
       [173, 465, 130, 237, 324, 419]], dtype=int32)

In [56]:
array1_1, array1_2, array1_3 = np.split(array1, [3, 5], axis=1)

In [57]:
array1_1

array([[196, 144, 321],
       [130, 438, 218],
       [357, 195, 104],
       [123, 470, 209],
       [126, 398, 379],
       [426, 256, 261],
       [270, 427, 461],
       [268, 481, 257],
       [315, 303, 215],
       [173, 465, 130]], dtype=int32)

In [58]:
array1_2

array([[195, 287],
       [419, 436],
       [321, 129],
       [223, 135],
       [292, 482],
       [409, 318],
       [124, 473],
       [320, 352],
       [380, 385],
       [237, 324]], dtype=int32)

In [59]:
array1_3

array([[407],
       [359],
       [381],
       [441],
       [169],
       [402],
       [266],
       [357],
       [391],
       [419]], dtype=int32)

### Load the dataset into numpy array

In [65]:
iris_array = np.genfromtxt(r"C:\Users\Lenovo\Desktop\Python-ML-Training-Arniko-college\Arniko_Day_session\Numpy_learning\iris.txt", delimiter=',', dtype=str)

In [66]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [67]:

features, labels = np.split(iris_array, [4], axis = 1)

In [74]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [69]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [70]:
features = features.astype(float)

In [71]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [72]:
features.dtype

dtype('float64')

## mean 

In [75]:
array1 = np.array([12, 14, 16, 13, 10])
mean = np.mean(array1)

In [76]:
mean

np.float64(13.0)

In [77]:
median = np.median(array1)
median

np.float64(13.0)

In [78]:
standard_deviation = np.std(array1)

In [79]:
standard_deviation


np.float64(2.0)

In [80]:
array_2 = np.random.randint(15, 25, size = (6, 4))

In [81]:
array_2

array([[24, 17, 15, 20],
       [21, 16, 17, 19],
       [18, 22, 17, 17],
       [18, 24, 23, 20],
       [24, 17, 23, 24],
       [15, 17, 22, 19]], dtype=int32)

In [82]:
array_2_mean = np.mean(array_2, axis=0)

In [83]:
array_2_mean

array([20.        , 18.83333333, 19.5       , 19.83333333])

In [84]:
features_mean = np.mean(features, axis = 0)

In [85]:
features_mean

array([5.84333333, 3.054     , 3.75866667, 1.19866667])